package sdmxdl.script.std;

import java.util.ArrayList;
import java.util.List;
import sdmxdl.Request;
import sdmxdl.script.Script;
import sdmxdl.script.ScriptOptions;
import sdmxdl.script.spi.ScriptGenerator;

/**
 * A script generated by a built-in generator for one of the test requests and options.
 */
@lombok.Value
class ScriptSample {

    String label;

    String language;

    Script script;

    @Override
    public String toString() {
        return label;
    }

    static List<ScriptSample> all() {
        List<ScriptSample> result = new ArrayList<>();
        for (ScriptGenerator generator : ScriptGeneratorsTest.generators()) {
            List<Request> requests = ScriptGeneratorsTest.requests();
            List<ScriptOptions> options = ScriptGeneratorsTest.options();
            for (int i = 0; i < requests.size(); i++) {
                for (int j = 0; j < options.size(); j++) {
                    Request request = requests.get(i);
                    result.add(new ScriptSample(
                            generator.getScriptTarget() + " "
                                    + request.getClass().getSimpleName() + "#" + i + " options#" + j,
                            generator.getScriptTarget().getLanguage(),
                            generator.generateScript(j == 0 ? "ECB" : "my source", request, options.get(j))));
                }
            }
        }
        return result;
    }
}
