name: Maven Java8+

on: [push, pull_request]

jobs:
  build-and-test-job:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        experimental: [false]
        include:
          - java: '>11'
            os: ubuntu-latest
            experimental: true
    
    name: JDK:${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Java 
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and test
        run: mvn -B package --file pom.xml
